# Generated by Django 6.0.8 on 2026-09-03 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_contingencia', 'En contingencia'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('cufe', models.CharField(blank=True, help_text='Lo asigna la DIAN vía el PT.', max_length=200)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('url_pdf', models.URLField(blank=True)),
                ('url_xml', models.URLField(blank=True)),
                ('codigo_qr', models.TextField(blank=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('respuesta_proveedor', models.JSONField(blank=True, help_text='Payload crudo del PT, para auditoría.', null=True)),
                ('proveedor_usado', models.CharField(blank=True, default='siigo', help_text='Histórico: con qué proveedor se facturó esta venta.', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='empresas.empresa')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'factura electrónica',
                'verbose_name_plural': 'facturas electrónicas',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='ix_factura_empresa_estado')],
            },
        ),
    ]
