# Generated by Django 6.0.8 on 2026-09-03 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'caja',
                'verbose_name_plural': 'cajas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_final_declarado', models.DecimalField(blank=True, decimal_places=2, help_text='Lo que el cajero cuenta físicamente al cerrar.', max_digits=12, null=True)),
                ('saldo_final_calculado', models.DecimalField(blank=True, decimal_places=2, help_text='Lo que el sistema calcula a partir de las ventas del turno.', max_digits=12, null=True)),
                ('abierto_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='caja.caja')),
            ],
            options={
                'verbose_name': 'turno de caja',
                'verbose_name_plural': 'turnos de caja',
                'ordering': ['-abierto_en'],
            },
        ),
    ]
