# Generated by Django 6.0.8 on 2026-09-03 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turnocaja',
            name='cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turnocaja',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='empresas.empresa'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uq_caja_empresa_nombre'),
        ),
        migrations.AddIndex(
            model_name='turnocaja',
            index=models.Index(fields=['empresa', 'estado'], name='ix_turno_empresa_estado'),
        ),
    ]
