# Generated by Django 6.0.8 on 2026-09-04 16:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnocaja',
            name='saldo_final_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que el cajero cuenta físicamente al cerrar.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='turnocaja',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
