# Generated by Django 6.0.8 on 2026-09-03 04:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='controla_stock',
            field=models.BooleanField(default=True, help_text='Si es False (servicios, recargas) el producto no genera ni valida movimientos de inventario.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Foto del stock. Solo lo escribe el servicio de movimientos (apps.inventario.services.aplicar_movimiento), nunca la API.', max_digits=12),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de mercancía'), ('venta', 'Salida por venta'), ('ajuste', 'Ajuste de inventario'), ('devolucion', 'Devolución de cliente'), ('salida', 'Salida (merma / daño / otro)')], max_length=12)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Con signo: + suma al stock, - resta. Ej.: venta de 2 => -2.', max_digits=12)),
                ('stock_resultante', models.DecimalField(decimal_places=2, help_text='Stock del producto justo después de aplicar este movimiento.', max_digits=12)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='empresas.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, help_text='Origen del movimiento cuando nace de una venta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['empresa', 'creado_en'], name='ix_movinv_empresa_creado'), models.Index(fields=['producto', 'creado_en'], name='ix_movinv_producto_creado')],
            },
        ),
    ]
