# Generated by Django 6.0.8 on 2026-09-04 16:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_controla_stock_alter_producto_stock_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='0 para productos exentos/excluidos. Tarifa real de ESTE producto.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, help_text='YA incluye IVA (precio al público). No es la base gravable.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
