# Generated by Django 6.0.8 on 2026-09-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_porcentaje_iva_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precios', to='inventario.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_precio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'histórico de precio',
                'verbose_name_plural': 'histórico de precios',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['producto', 'creado_en'], name='ix_histprecio_producto_creado')],
            },
        ),
    ]
