# Generated by Django 6.0.8 on 2026-09-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_comercial', models.CharField(blank=True, max_length=255)),
                ('nit', models.CharField(max_length=15, unique=True)),
                ('digito_verificacion', models.CharField(max_length=1)),
                ('regimen_tributario', models.CharField(choices=[('responsable_iva', 'Responsable de IVA'), ('no_responsable_iva', 'No responsable de IVA'), ('regimen_simple', 'Régimen simple de tributación')], max_length=25)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email_facturacion', models.EmailField(blank=True, max_length=254)),
                ('resolucion_prefijo', models.CharField(blank=True, max_length=10)),
                ('resolucion_numero', models.CharField(blank=True, max_length=50)),
                ('resolucion_rango_desde', models.PositiveIntegerField(blank=True, null=True)),
                ('resolucion_rango_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('resolucion_vigencia_hasta', models.DateField(blank=True, null=True)),
                ('siigo_api_username', models.CharField(blank=True, max_length=255)),
                ('siigo_api_access_key', models.CharField(blank=True, max_length=255)),
                ('siigo_partner_id', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
