# Generated by Django 6.0.8 on 2026-09-04 16:46

import apps.empresas.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='siigo_api_access_key',
            field=apps.empresas.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='siigo_api_username',
            field=apps.empresas.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='siigo_partner_id',
            field=apps.empresas.fields.EncryptedTextField(blank=True, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
