# Generated by Django 6.0.8 on 2026-09-03 03:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('empresas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], max_length=20)),
                ('es_de_contado', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, help_text='NULL = consumidor final.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='terceros.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='empresas.empresa')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.turnocaja')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de venta',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'creada_en'], name='ix_venta_empresa_creada'),
        ),
    ]
