# Generated by Django 6.0.8 on 2026-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada')], default='completada', max_length=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
