# Generated by Django 6.0.8 on 2026-09-04 17:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_siigo_api_access_key_and_more'),
        ('ventas', '0003_venta_anulada_en_venta_estado_venta_motivo_anulacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Foto del %IVA del producto al momento de la venta. Necesaria para reportes de IVA correctos: si el IVA del producto cambia después, esta línea no debe verse afectada.', max_digits=5),
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'nota crédito',
                'verbose_name_plural': 'notas crédito',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cuánto de esa línea se devuelve (puede ser parcial).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('detalle_venta', models.ForeignKey(help_text='La línea original de la venta que se está devolviendo.', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.detalleventa')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.notacredito')),
            ],
            options={
                'verbose_name': 'línea de nota crédito',
                'verbose_name_plural': 'líneas de nota crédito',
            },
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['empresa', 'creada_en'], name='ix_notacred_empresa_creada'),
        ),
    ]
